admin_search:
  path: /admin/search
  controller: App\Controller\Admin\AdminCarController::adminSearch

front_search:
  path: search
  controller: App\Controller\Front\CarController::frontSearch

car_list:
  path: cars
  controller: App\Controller\Front\CarController::carList

car_show:
  path: car/{id}
  controller: App\Controller\Front\CarController::carShow

admin_delete_car:
  path: admin/delete/car/{id}
  controller: App\Controller\Admin\AdminCarController::deleteCar

admin_car_create:
  path: admin/create/car
  controller: App\Controller\Admin\AdminCarController::createCar

admin_update_car:
  path: admin/update/car/{id}
  controller: App\Controller\Admin\AdminCarController::carUpdate

admin_car_show:
  path: admin/car/{id}
  controller: App\Controller\Admin\AdminCarController::carShow

admin_car_list:
  path: admin/cars
  controller: App\Controller\Admin\AdminCarController::carList

brand_list:
  path: brands
  controller: App\Controller\Front\BrandController::brandList

brand_show:
  path: brand/{id}
  controller: App\Controller\Front\BrandController::brandShow

admin_brand_list:
  path: admin/brands
  controller: App\Controller\Admin\AdminBrandController::adminListBrand

admin_brand_show:
  path: admin/brand/{id}
  controller: App\Controller\Admin\AdminBrandController::adminShowBrand

update_brand:
  path: admin/update/brand/{id}
  controller: App\Controller\Admin\AdminBrandController::adminUpdateBrand

create_brand:
  path: admin/create/brand
  controller: App\Controller\Admin\AdminBrandController::adminBrandCreate

delete_brand:
  path: admin/delete/brand/{id}
  controller: App\Controller\Admin\AdminBrandController::adminDeleteBrand

groupe_list:
  path: groupes
  controller: App\Controller\Front\GroupController::groupeList

groupe_show:
  path: groupe/{id}
  controller: App\Controller\Front\GroupController::groupShow

admin_groupe_list:
  path: admin/groupes
  controller: App\Controller\Admin\AdminGroupController::adminListGroup

admin_groupe_create:
  path: admin/create/groupe/
  controller: App\Controller\Admin\AdminGroupController::adminGroupCreate

admin_groupe_update:
  path: admin/update/groupe/{id}
  controller: App\Controller\Admin\AdminGroupController::adminUpdateGroup

admin_delete_groupe:
  path: admin/delete/groupe/{id}
  controller: App\Controller\Admin\AdminGroupController::adminDeleteGroup

admin_groupe_show:
  path: admin/groupe/{id}
  controller: App\Controller\Admin\AdminGroupController::adminShowGroup

create_image:
  path: admin/create/image
  controller: App\Controller\Admin\AdminImageController::createImage

update_image:
  path: admin/update/image/{id}
  controller: App\Controller\Admin\AdminImageController::updateImage

delete_image:
  path: admin/delete/image/{id}
  controller: App\Controller\Admin\AdminImageController::deleteImage

image_list:
  path: admin/images
  controller: App\Controller\Admin\AdminImageController::imageList

image_show:
  path: admin/image/{id}
  controller: App\Controller\Admin\AdminImageController::image_show

contact:
  path: contact
  controller: App\Controller\Front\MessageController::contact

message:
  path: message
  controller: App\Controller\Front\MessageController::message